apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hazelcast
  labels:
    app.kubernetes.io/name: hazelcast
spec:
  replicas: 3
  serviceName: hazelcast-service
  selector:
    matchLabels:
      app.kubernetes.io/name: hazelcast
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hazelcast
    spec:
      containers:
      - name: hazelcast
        image: hazelcast/hazelcast:4.0
        ports:
        - name: hazelcast
          containerPort: 5701
        livenessProbe:
          httpGet:
            path: /hazelcast/health/node-state
            port: 5701
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /hazelcast/health/node-state
            port: 5701
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 10
        volumeMounts:
        - name: hazelcast-storage
          mountPath: /data/hazelcast
        env:
        - name: JAVA_OPTS
          value: "-Dhazelcast.config=/data/hazelcast/hazelcast.yaml"
      volumes:
      - name: hazelcast-storage
        configMap:
          name: hazelcast-configuration
