hazelcast:
  cluster-name: nyc-cluster
  network:
    port:
      port-count: 20
      auto-increment: true
      port:
        5701
    join:
      multicast:
        enabled: false
      tcp-ip:
        enabled: true
        member-list:
          - nyc-cluster-1
  wan-replication:
    replicate-to-lon:
      batch-publisher:
        lonPublisher:
          cluster-name: london-cluster
          target-endpoints: "london-cluster-1:5701"
  map:
    shopSessions:
      wan-replication-ref:
        replicate-to-lon:
          merge-policy-class-name: PutIfAbsentMergePolicy
      backup-count: 1
      # because we are modifying IMap's config not via sessionMapConfigCustomizer, we need to add the index manually
      indexes:
        - type: HASH
          attributes:
            - "principalName"
