hazelcast:
  jet:
    enabled: true
    resource-upload-enabled: true
  map:
    "*_request":
      event-journal:
        enabled: true
        capacity: 100000
      eviction:
        eviction-policy: RANDOM
        size: 1
        max-size-policy: PER_PARTITION
